CREATE DATABASE QLGVTR			

USE QLGVTR

USE master

CREATE TABLE GIAOVIEN
(
	MAGV CHAR(3),
	HOTEN NVARCHAR(50),
	LUONG NUMERIC(5,1),
	PHAI NVARCHAR(3),
	NGSINH DATE,
	DIACHI NVARCHAR(70),
	GVQLCM CHAR(3),
	MABM NVARCHAR(4),
	PRIMARY KEY (MAGV)
)

CREATE TABLE THAMGIADT
(
	MAGV CHAR(3), 
	MADT CHAR(3),
	STT INT,
	PHUCAP NUMERIC (2,1),
	KETQUA NVARCHAR(5),
	PRIMARY KEY (MAGV, MADT, STT),
)
CREATE TABLE CONGVIEC(
	MADT CHAR(3),
	SOTT INT,
	TENCV NVARCHAR(25),
	NGAYBD DATE,
	NGAYKT DATE,
	PRIMARY KEY (MADT, SOTT)
)
CREATE TABLE DETAI(
	MADT CHAR(3),
	TENDT NVARCHAR(35),
	CAPQL NVARCHAR(15),
	KINHPHI NUMERIC(6,1),
	NGAYBD DATE,
	NGAYKT DATE,
	MACD CHAR(4),
	GVCNDT CHAR(3),
	PRIMARY KEY (MADT)
)
CREATE TABLE CHUDE(
	MACD CHAR(4),
	TENCD NVARCHAR(35),
	PRIMARY KEY (MACD)
)
CREATE TABLE NGUOITHAN(
	MAGV CHAR(3),
	TEN NVARCHAR(10),
	NGSINH DATE,
	PHAI NVARCHAR(3),
	PRIMARY KEY (MAGV,TEN)
)
CREATE TABLE GV_DT(
	MAGV CHAR(3),
	DIENTHOAI CHAR(11),
	PRIMARY KEY (MAGV,DIENTHOAI)
)
CREATE TABLE BOMON(
	MABM VARCHAR(4),
	TENBM NVARCHAR(35),
	PHONG CHAR(3),
	DIENTHOAI CHAR(11),
	TRUONGBM CHAR(3),
	MAKHOA VARCHAR(4),
	NGAYNHANCHUC DATE,
	PRIMARY KEY (MABM)
)
CREATE TABLE KHOA(
	MAKHOA VARCHAR(4),
	TENKHOA NVARCHAR(35),
	NAMTL INT,
	DIENTHOAI INT,
	TRUONGKHOA CHAR(3),
	NGAYNHANCHUC DATE,
	PRIMARY KEY (MAKHOA)
)

SELECT * FROM GIAOVIEN 
//XOA BANG
DROP TABLE GIAOVIEN
DROP TABLE THAMGIADT
DROP TABLE BOMON

//tao_foreign_key
ALTER TABLE THAMGIADT
ADD CONSTRAINT FK_TG_GV
FOREIGN KEY (MAGV) REFERENCES GIAOVIEN(MAGV)

ALTER TABLE THAMGIADT
ADD CONSTRAINT FK_TG_GV
FOREIGN KEY (MADT) REFERENCES CONGVIEC(MADT)

ALTER TABLE THAMGIADT
ADD CONSTRAINT FK_TG_GV
FOREIGN KEY (STT) REFERENCES CONGVIEC(SOTT)

ALTER TABLE CONGVIEC
ADD CONSTRAINT FK_TG_GV
FOREIGN KEY (MADT) REFERENCES DETAI(MADT)

ALTER TABLE DETAI
ADD CONSTRAINT FK_TG_GV
FOREIGN KEY (GVCNDT) REFERENCES GIAOVIEN(MAGV)

ALTER TABLE DETAI
ADD CONSTRAINT FK_TG_GV
FOREIGN KEY (MACD) REFERENCES CHUDE(MACD)

ALTER TABLE NGUOITHAN
ADD CONSTRAINT FK_TG_GV
FOREIGN KEY (MAGV) REFERENCES GIAOVIEN(MAGV)

ALTER TABLE GV_DT
ADD CONSTRAINT FK_TG_GV
FOREIGN KEY (MAGV) REFERENCES GIAOVIEN(MAGV)

ALTER TABLE BOMON
ADD CONSTRAINT FK_TG_GV
FOREIGN KEY (MABM) REFERENCES KHOA(MABM)

ALTER TABLE BOMON
ADD CONSTRAINT FK_TG_GV
FOREIGN KEY (TRUONGBM) REFERENCES GIAOVIEN(MAGV)

ALTER TABLE GIAOVIEN
ADD CONSTRAINT FK_TG_GV
FOREIGN KEY (MABM) REFERENCES BOMON(MABM)

ALTER TABLE GIAOVIEN
ADD CONSTRAINT FK_TG_GV
FOREIGN KEY (GVQLCM) REFERENCES GIAOVIEN(MAGV)

//xoa foreign key
ALTER TABLE THAMGIADT
DROP CONSTRAINT FK_TG_GV